name: Socket SDK CI

on:
  push:
    branches-ignore:
      - 'dev'



jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        registry-url: https://npm.pkg.github.com/
        scope: '@socketsupply'

    - name: Install Socket SDK deps
      run: |
        sudo apt install software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt install gcc-11 g++-11 libwebkit2gtk-4.0-dev libcurl4-openssl-dev

    - name: install ssc
      run: |
        ./bin/install.sh
      env:
        CXX: g++-11

    - name: Check if Socket SDK has a correct version
      run: |
        ./bin/ci_version_check.sh

    - name: install an example app
      run: |
        git config --global user.email "devops@optool.co"
        git config --global user.name "Optool Github Actions"
        git clone --depth 1 git@github.com:socketsupply/socket-sdk-examples.git
        cd socket-sdk-examples/desktop-tonic/ && npm install
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}

    - name: compile example desktop
      run: |
        ssc compile ./socket-sdk-examples/desktop-tonic/
      env:
        CI: true
        CXX: g++-11

    - name: Run example desktop tests
      run: |
        xvfb-run --server-args="-screen 0 1920x1080x24" ssc compile --test=1 -r  ./socket-sdk-examples/desktop-tonic/
      env:
        CI: true
        CXX: g++-11

  build_on_win:
    runs-on: windows-2022
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.event.inputs.tag }}
    # The webfactory/ssh-agent module does not work on Windows anymore
    # I do not recommend touching this SSH stuff, i spend two days
    # tweaking it just to get it to work on windows -.-

    - name: Configure SSH
      run: Set-Service ssh-agent -StartupType Manual

    - name: Start SSH
      run: Start-Service ssh-agent

    - name: Add SSH key
      run: echo $env:SSH_PRIVATE_KEY | ssh-add -
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add github.com to known_hosts
      run: |
        mkdir ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: install ssc
      run: |
        ./bin/install.ps1

        echo "::add-path::$env:LOCALAPPDATA\Programs\socketsupply\src"
        echo "$env:LOCALAPPDATA\Programs\socketsupply\src" >> $env:GITHUB_PATH
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Check if ssc has a correct version
      run: |
        ./bin/ci_version_check.ps1

    - name: install an example app
      run: |
        git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"
        git config --global http.postBuffer 157286400
        git config --global core.compression 0

        git config --global user.email "devops@optool.co"
        git config --global user.name "Optool Github Actions"
        git clone --depth 1 git@github.com:socketsupply/socket-sdk-examples.git
        cd socket-sdk-examples/desktop-tonic/ && npm install
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}

    - name: compile example desktop
      run: |
        ssc compile ./socket-sdk-examples/desktop-tonic/
      env:
        CI: true

    - name: Run example desktop tests
      run: |
        ssc compile --test=1 -r ./socket-sdk-examples/desktop-tonic/
      env:
        CI: true

  build_on_mac:
    runs-on: macOS-11
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: install automake
      run: brew install automake

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        registry-url: https://npm.pkg.github.com/
        scope: '@socketsupply'

    - name: install ssc
      run: |
        ./bin/install.sh

    - name: Check if ssc has a correct version
      run: |
        ./bin/ci_version_check.sh

    - name: install an example app
      run: |
        git config --global user.email "devops@optool.co"
        git config --global user.name "Optool Github Actions"
        git clone --depth 1 git@github.com:socketsupply/socket-sdk-examples.git
        cd socket-sdk-examples/desktop-tonic/ && npm install
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}

    - name: compile example desktop
      run: |
        ssc compile ./socket-sdk-examples/desktop-tonic/
      env:
        CI: true

    - name: Run example desktop tests
      run: |
        ssc compile --test=1 -r ./socket-sdk-examples/desktop-tonic/
      env:
        CI: true

  build_on_ios:
    runs-on: macOS-11
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: install automake
      run: brew install automake

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        registry-url: https://npm.pkg.github.com/
        scope: '@socketsupply'

    - name: cross-compile
      run: |
        ./bin/install.sh ios

    - name: Check if ssc has a correct version
      run: |
        ./bin/ci_version_check.sh

    - name: install an example app
      run: |
        git config --global user.email "devops@optool.co"
        git config --global user.name "ssc Github Actions"
        git clone --depth 1 https://github.com/socketsupply/socket-sdk-examples.git
        cd socket-sdk-examples/tonic-ios/ && npm install
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}

    - name: compile example ios
      run: |
        ssc compile --target=iossimulator ./socket-sdk-examples/tonic-ios/
      env:
        CI: true
